name:                servant-playground
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- servant-swagger
- swagger2
- servant-swagger-ui
- hasql
- warp
- aeson
- text
- bytestring
- lens

library:
  source-dirs: src
  default-extensions:
  - DataKinds
  - TypeOperators
  - DeriveGeneric
  - OverloadedStrings
  - LambdaCase
  ghc-options:
  - -F -pgmF=record-dot-preprocessor
  - -Wall
  - -Wno-name-shadowing

executables:
  servant-playground-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -F -pgmF=record-dot-preprocessor
    dependencies:
    - servant-playground
    default-extensions:
    - DataKinds
    - TypeOperators
    - DeriveGeneric
    - OverloadedStrings
    - LambdaCase

tests:
  servant-playground-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-playground
